---
openapi: 3.0.1
info:
  title: Cfops API
  description: Esta é uma API para gerenciar Cfops.
  contact:
    name: Suporte Cfops API
    url: http://cfopsapi.com/contact
    email: techsupport@cfopsapi.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
  - name: Cfops
    description: Todos as operações permitidas para o recurso Cfops
paths:
  /dfe/v1/cfops:
    get:
      tags:
        - Cfops
      summary: Listar todos os cfops cadastrados
      parameters:
        - name: limit
          in: query
          description: Número máximo de registros a serem retornados
          required: true
          schema:
            default: 20
            type: integer
          example: '20'
        - name: offset
          in: query
          description: Número da página a ser retornada
          required: true
          schema:
            default: 1
            type: integer
          example: '1'
      responses:
        '404':
          description: Não foi encontrado nenhum cfop
        '500':
          description: Erro Interno no servidor
        '200':
          description: Cfops encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CfopsResposta'
              example:
                cfops:
                  - id: 1101
                    nome: 'Compra para industrialização ou produção rural (NR Ajuste SINIEF 05/2005) (Decreto 28.868/2006)'
                    inicioVigencia: '2006-01-01'
                    indNFe: 1
                    indComunica: 0
                    indTransp: 0
                    indDevol: 0
                    indRetor: 0
                    indAnula: 0
                    indeRemes: 0
                    indComb: 0
                  - id: 1102
                    nome: 'Compra para comercialização'
                    inicioVigencia: '2006-01-01'
                    indNFe: 1
                    indComunica: 0
                    indTransp: 0
                    indDevol: 0
                    indRetor: 0
                    indAnula: 0
                    indeRemes: 0
                    indComb: 0
          links:
            incluir:
              operationId: incluir
              description: Incluir um novo cfop
    post:
      tags:
        - Cfops
      summary: Permite incluir um novo cfop
      requestBody:
        description: Dados do cfop a ser incluído
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cfops'
            example:
              id: 1101
              nome: 'Compra para industrialização ou produção rural (NR Ajuste SINIEF 05/2005) (Decreto 28.868/2006)'
              inicioVigencia: '2006-01-01'
              indNFe: 1
              indComunica: 0
              indTransp: 0
              indDevol: 0
              indRetor: 0
              indAnula: 0
              indeRemes: 0
              indComb: 0
      responses:
        '500':
          description: Erro interno no servidor
        '406':
          description: País não incluído
        '204':
          description: País incluído com sucesso
          links:
            self:
              operationId: buscarPorId
              parameters:
                id: $response.body#/id
              description: Buscar cfop pelo ID
  /dfe/v1/cfops/{id}:
    get:
      tags:
        - Cfops
      summary: Busca um cfop pelo ID/código/identificador.
      parameters:
        - name: id
          in: path
          description: Código/Identificador do cfop a ser buscado
          required: true
          schema:
            type: integer
          example: 1101
      responses:
        '500':
          description: Erro Interno no servidor
        '404':
          description: País não encontrado
          links:
            buscar_todos:
              operationId: buscarTodos
              description: Buscar lista de cfop
        '200':
          description: Cfops encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cfops'
              example:
                id: 1101
                nome: 'Compra para industrialização ou produção rural (NR Ajuste SINIEF 05/2005) (Decreto 28.868/2006)'
                inicioVigencia: '2006-01-01'
                indNFe: 1
                indComunica: 0
                indTransp: 0
                indDevol: 0
                indRetor: 0
                indAnula: 0
                indeRemes: 0
                indComb: 0
          links:
            buscar_todos:
              operationId: buscarTodos
              description: Buscar lista de cfop
            atualizar:
              operationId: atualizar
              parameters:
                id: $response.body#/id
              description: Atualizar dados do cfop
            excluir:
              operationId: remover
              parameters:
                id: $response.body#/id
              description: Remover um cfop pelo ID
    put:
      tags:
        - Cfops
      summary: Permite modificar os dados de um cfop
      parameters:
        - name: id
          in: path
          description: Código/Identificador do cfop a ser modificado
          required: true
          schema:
            type: integer
          example: 1101
      requestBody:
        description: Dados do cfop a ser modificado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cfops'
            example:
              nome: 'Compra para industrialização ou produção rural (NR Ajuste SINIEF 05/2005) (Decreto 28.868/2006)'
              inicioVigencia: '2019-01-01'
              indNFe: 1
              indComunica: 0
              indTransp: 0
              indDevol: 0
              indRetor: 0
              indAnula: 0
              indeRemes: 0
              indComb: 1
      responses:
        '404':
          description: País não encontrado para atualizar
        '500':
          description: Erro Interno no servidor
        '412':
          description: O código do País informado não esta correto
        '204':
          description: País atualizado com sucesso
          links:
            self:
              operationId: buscarPorId
              parameters:
                id: $response.body#/id
              description: Buscar cfop pelo ID
    delete:
      tags:
        - Cfops
      summary: Excluí um cfop através do ID/codigo/identificador
      parameters:
        - name: id
          in: path
          description: Código/Identificador do cfop a ser removido
          required: true
          schema:
            type: integer
          example: '1601'
      responses:
        '500':
          description: Erro Interno no servidor
          content:
            application/json: {}
        '404':
          description: País não encontrado para excluir
          content:
            application/json: {}
        '204':
          description: País excluído com sucesso
          content:
            application/json: {}
          links:
            buscar_todos:
              operationId: buscarTodos
              description: Buscar lista de cfop
components:
  schemas:
    Cfops:
      description: Esquema da entidade cfops.
      type: object
      properties:
        Id:
          format: int64
          description: 'Código/identificador do cfop.'
          type: integer
        nome:
          description: Nome do cfop.
          type: string
        indNfe:
          description: Indica NF-e.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indComunica:
          description: Indicador comunicação.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indTransp:
          description: Indicador transporte.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indDevol:
          description: Indicador Devolução.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indRetor:
          description: Indicador Retorno.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indAnula:
          description: Indicador anulação.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indRemes:
          description: Indicador remessa.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        indComb:
          description: Indicador combustivel.
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10
        inicioVigencia:
          description: Data de Inicio de vigência de validade CFOP
          type: string
          format: date
          example: '2006-01-01'
        fimVigencia:
          description: Data Final da vigência de validade do CFOP
          type: string
          format: date
          example: '2006-01-01'
      example:
        id: 1101
        nome: 'Compra para industrialização ou produção rural (NR Ajuste SINIEF 05/2005) (Decreto 28.868/2006)'
        indNfe: 1
        indComunica: 0
        indTransp: 0
        indDevol: 0
        indRetor: 0
        indAnula: 0
        indRemes: 0
        indComb: 0
        inicioVigencia: '2006-01-01'

    CfopsResposta:
      description: Schema da resposta padrão metodo buscarTodos.
      type: object
      properties:
        cfops:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Cfops'
        version:
          description: Versão do schema de resposta.
          type: string
          default: '3.0.0'
